source 'https://github.com/CocoaPods/Specs.git'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

platform :ios, '10.0'
use_frameworks!

target 'Runner' do
project 'Runner.xcodeproj'

  pod 'IQKeyboardManagerSwift', '=6.1.1'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        puts "Updating #{target.name}"
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
            config.build_settings['SWIFT_SWIFT3_OBJC_INFERENCE'] = 'Default'
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
